/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_brotherhood_o2o_explore_helper_ImageBlur */

#ifndef _Included_com_brotherhood_o2o_explore_helper_ImageBlur
#define _Included_com_brotherhood_o2o_explore_helper_ImageBlur
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_brotherhood_o2o_explore_helper_ImageBlur
 * Method:    blurIntArray
 * Signature: ([IIII)V
 */
JNIEXPORT void JNICALL Java_com_brotherhood_o2o_explore_helper_ImageBlur_blurIntArray
  (JNIEnv *, jclass, jintArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
